[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.33"
evm_version = "cancun"
via_ir = true
gas_reports = ["*"]
ignored_warnings_from = ["lib/solmate", "lib/forge-std"]

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.ci.fuzz]
runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
